stages:
  ingest:
    cmd: uv run python -m trend_analysis.pipelines.data_ingestion
    deps:
      - trend_analysis/pipelines/data_ingestion.py
    outs:
      - data/raw
  preprocess:
    cmd: uv run python -m trend_analysis.pipelines.preprocess
    deps:
      - data/raw
      - trend_analysis/pipelines/preprocess.py
    params:
      - preprocessing
    outs:
      - data/processed
  train:
    cmd: uv run python -m trend_analysis.pipelines.train
    deps:
      - data/processed
      - trend_analysis/pipelines/train.py
    params:
      - train
      - mlflow
    outs:
      - models/trend_analysis_model.pkl
  inference:
    cmd: uv run python -m trend_analysis.pipelines.inference
    deps:
      - data/processed
      - models/trend_analysis_model.pkl
      - trend_analysis/pipelines/inference.py
    outs:
      - data/results/inferences.csv
