stages:
  ingest:
    cmd: uv run python -m ml_orderflow.pipelines.data_ingestion
    deps:
      - ml_orderflow/pipelines/data_ingestion.py
    outs:
      - data/raw
  preprocess:
    cmd: uv run python -m ml_orderflow.pipelines.preprocess
    deps:
      - data/raw
      - ml_orderflow/pipelines/preprocess.py
    params:
      - preprocessing
    outs:
      - data/processed
  train:
    cmd: uv run python -m ml_orderflow.pipelines.train
    deps:
      - data/processed
      - ml_orderflow/pipelines/train.py
    params:
      - train
      - mlflow
    outs:
      - models/ml_orderflow.pkl
  inference:
    cmd: uv run python -m ml_orderflow.pipelines.inference
    deps:
      - data/processed
      - models/ml_orderflow.pkl
      - ml_orderflow/pipelines/inference.py
    outs:
      - data/results/inferences.csv
