base:
  project: ml_orderflow
  data_dir: data
  model_dir: models
  log_dir: logs

data_ingestion:
  source: mt5  # options: mt5, mexc
  raw_data_path: data/raw
  test_size: 0.2
  mexc:
    symbols: ["BTC/USDT", "ETH/USDT", "SOL/USDT"]
    timeframes: ["1h", "4h", "1d", "1w"]
    limit: 500
  mt5:
    symbols: ["BTCUSD", "ETHUSD", "XAUUSD", "GBPUSD"]
    timeframes: ["H1", "H4", "D1", "W1"]  # mt5 timeframe constants usually needed, will handle string conversion in code
    n_bars: 1000

preprocessing:
  processed_data_path: data/processed
  lrc_period: 100
  
  # Liquidity Sentiment Profile
  lsp_window: 100
  lsp_bins: 20
  
  # Candlestick Patterns (requires pandas-ta-classic)
  enable_candlestick_patterns: false  # Set to true to enable (adds many columns)
  
  # Target Configuration
  target_column: "next_return"  # Name of the target column to create
  target_source: "returns"  # Source column to shift (options: returns, close, volume, log_returns, etc.)
  target_window: 4  # How many periods ahead to predict
  
  # Examples:
  # - Predict next return: target_source="returns", target_window=1
  # - Predict next close price: target_source="close", target_window=1
  # - Predict volume 3 steps ahead: target_source="volume", target_window=3
  volatility_windows: [7, 24]
  sma_windows: [20, 50]
  rsi_window: 14
  min_bars: 150

  enable_multivariate: false

  # Multivariate Configuration
  # Defines the SINGLE Target and the Contexts to merge onto it.
  multivariate_config:
    target_timeframe: "H1" # The base timeframe for predictions
    target_symbol: "ETHUSD" # The base symbol for predictions

    # Context Dictionary: Symbol -> List of Timeframes
    context:
      BTCUSD: ["H1", "H4"]  # Merge BTC H1 and H4
      GBPUSD: ["H1"]        # Merge GBP H1
      ETHUSD: ["H4"]        # Merge ETH H4 (cross-timeframe self-context)

train:
  model_name: "ml_orderflow"
  model_type: "xgboost"  # Options: xgboost, lightgbm, randomforest, nhits, lstm
  lags: [1, 2, 3, 7, 14, 21]
  forecast_horizon: 1  # N-step ahead forecasting
  input_size: 128 # Context window size for DL models
  use_static_features: false  # Whether to use static features (symbol, timeframe, etc.)

# Robustness & Validation
validation:
  enforce_schema: true
  required_columns: ["open", "high", "low", "close", "volume"]
  anomaly_protection:
    check_zscore: true
    zscore_threshold: 4.0
    action: "warn" # options: "warn", "drop"

# LLM Configuration
llm:
  provider: "gemini" # options: gemini, openai, dummy
  model: "gemini-2.5-flash"  # Stable models: gemini-pro, gemini-1.5-flash, gemini-1.5-pro
  temperature: 0.7
  max_output_tokens: 1024
  
  # OpenAI specific (if provider is openai)
  openai_model: "gpt-3.5-turbo"  # or gpt-4
  
  # Caching
  cache_enabled: true
  cache_ttl_seconds: 3600  # 1 hour
  
  # Advanced prompting
  use_technical_context: true
  include_market_regime: true
  detect_anomalies: true  # Enable anomaly detection (price spikes, volume anomalies)
  anomaly_z_threshold: 3.0  # Z-score threshold for anomaly detection

# Robustness Configuration
robustness:
  circuit_breaker:
    failure_threshold: 5
    timeout_seconds: 60
    half_open_max_calls: 3
  
  retry:
    max_attempts: 3
    base_delay_seconds: 2
    max_delay_seconds: 30
    jitter: true
  
  timeouts:
    data_fetch_seconds: 30
    model_training_minutes: 60
    inference_seconds: 10

mlflow:
  tracking_uri: sqlite:///mlflow.db
  experiment_name: ml_orderflow
  model_registry_name: ml_orderflow

schedule:
  interval_minutes: 60
  misfire_grace_time: 60
  enabled: true
